require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Enable modular headers globally for all pods
use_modular_headers!

platform :ios, '15.1' # Updated minimum iOS version
prepare_react_native_project!

# Conditional framework linking
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Zify' do
  config = use_native_modules!

  # Flags change depending on the env values
  flags = get_default_flags()

  # Explicitly add Yoga before use_react_native!
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Firebase pods
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Core'

  # React Native permissions (corrected paths)
  # permissions_path = '../node_modules/react-native-permissions'
  # pod 'Permission-Camera', :path => permissions_path
  # pod 'Permission-LocationWhenInUse', :path => permissions_path
  # pod 'Permission-Notifications', :path => permissions_path
  
  # Other pods
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Architecture and build settings
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings["CLANG_ENABLE_MODULES"] = "YES"
      config.build_settings["GCC_WARN_INHIBIT_ALL_WARNINGS"] = "YES"
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "15.1"
    end
    
    # Set deployment target for all targets
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        if target.name == 'React-Core.common'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_NEW_ARCH_ENABLED=1'
        end
      end
    end
  end
end